version: "3"

services:
  app:
    container_name: app
    restart: unless-stopped
    image: stt_app
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./models:/models
    devices:
      - /dev/snd:/dev/snd
    ports:
      - 8501:8501
