version: "3"

services:
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - ./main.py:/main.py
    command: bash -c "streamlit run main.py"
    ports:
      - 8501:8501
